_wandb:
    value:
        cli_version: 0.25.1
        e:
            1db8ekkyz151angvyqeb7li6uaooqfic:
                codePath: scripts/train_overfit.py
                codePathLocal: scripts/train_overfit.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "157396975616"
                        used: "73633107968"
                email: u1588823@gcloud.utah.edu
                executable: /local/scratch/scratch-hd/desmond/miniconda3/envs/dreamer_mri/bin/python
                git:
                    commit: 74452766f4b3b264e7e6806b2778acb466b3990f
                    remote: https://github.com/deskk/DreamerMRI.git
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-1d3099f9-4adb-3413-2068-559ccae291a8
                host: desmond
                memory:
                    total: "66515582976"
                os: Linux-6.8.0-107-generic-x86_64-with-glibc2.39
                program: /local/scratch/scratch-hd/desmond/aai-project/scripts/train_overfit.py
                python: CPython 3.10.20
                root: /local/scratch/scratch-hd/desmond/aai-project
                startedAt: "2026-04-10T18:33:21.185969Z"
                writerId: 1db8ekkyz151angvyqeb7li6uaooqfic
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 12
                - 105
            "2":
                - 1
                - 12
                - 105
            "3":
                - 13
                - 35
                - 41
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
